set(LIBNAME libaws-sdk-cpp)
set(DEPS libz libopenssl libboost)

ADD_OSQUERY_NEWDEP(${LIBNAME})
GET_NEWDEPS(PROJECT_DEPS ${DEPS})

ExternalProject_Add(third-party-${LIBNAME}
  URL https://github.com/aws/aws-sdk-cpp/archive/1.4.55.tar.gz
  INSTALL_DIR ${THIRD_PARTY_PREFIX}
  STEP_TARGETS build install
  DEPENDS ${PROJECT_DEPS}
  CONFIGURE_COMMAND
    cmake
      -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
      -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
      -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_LIBRARY_PATH=<INSTALL_DIR>/lib
      -DZLIB_INCLUDE_DIR=<INSTALL_DIR>/include
      -DOPENSSL_INCLUDE_DIR=<INSTALL_DIR>/include
      -DOPENSSL_SSL_LIBRARY=<INSTALL_DIR>/lib/libssl.a
      -DOPENSSL_CRYPTO_LIBRARY=<INSTALL_DIR>/lib/libcrypto.a
      -DSTATIC_LINKING=1
      -DNO_HTTP_CLIENT=1
      -DMINIMIZE_SIZE=ON
      -DBUILD_SHARED_LIBS=OFF
      -DENABLE_TESTING=OFF
      -DAUTORUN_UNIT_TESTS=OFF
      -DBUILD_ONLY=firehose$<SEMICOLON>kinesis$<SEMICOLON>sts$<SEMICOLON>ec2
      <SOURCE_DIR>
  BUILD_COMMAND
    make -j10
  INSTALL_COMMAND
    make install
  EXCLUDE_FROM_ALL ON
)
